INSERT INTO regions (code, name, level, lat, lng) VALUES ('ACEH', 'Aceh', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SUMATERA_UTARA', 'Sumatera Utara', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SUMATERA_BARAT', 'Sumatera Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('RIAU', 'Riau', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('JAMBI', 'Jambi', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SUMATERA_SELATAN', 'Sumatera Selatan', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('BENGKULU', 'Bengkulu', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('LAMPUNG', 'Lampung', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KEPULAUAN_BANGKA_BELITUNG', 'Kepulauan Bangka Belitung', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KEPULAUAN_RIAU', 'Kepulauan Riau', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('DKI_JAKARTA', 'DKI Jakarta', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('JAWA_BARAT', 'Jawa Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('JAWA_TENGAH', 'Jawa Tengah', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('DI_YOGYAKARTA', 'DI Yogyakarta', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('JAWA_TIMUR', 'Jawa Timur', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('BANTEN', 'Banten', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('BALI', 'Bali', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('NUSA_TENGGARA_BARAT', 'Nusa Tenggara Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('NUSA_TENGGARA_TIMUR', 'Nusa Tenggara Timur', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KALIMANTAN_BARAT', 'Kalimantan Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KALIMANTAN_TENGAH', 'Kalimantan Tengah', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KALIMANTAN_SELATAN', 'Kalimantan Selatan', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KALIMANTAN_TIMUR', 'Kalimantan Timur', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('KALIMANTAN_UTARA', 'Kalimantan Utara', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SULAWESI_UTARA', 'Sulawesi Utara', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SULAWESI_TENGAH', 'Sulawesi Tengah', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SULAWESI_SELATAN', 'Sulawesi Selatan', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SULAWESI_TENGGARA', 'Sulawesi Tenggara', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('GORONTALO', 'Gorontalo', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('SULAWESI_BARAT', 'Sulawesi Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('MALUKU', 'Maluku', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('MALUKU_UTARA', 'Maluku Utara', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA_BARAT', 'Papua Barat', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA', 'Papua', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA_SELATAN', 'Papua Selatan', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA_TENGAH', 'Papua Tengah', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA_PEGUNUNGAN', 'Papua Pegunungan', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;
INSERT INTO regions (code, name, level, lat, lng) VALUES ('PAPUA_BARAT_DAYA', 'Papua Barat Daya', 'provinsi', 0, 0) ON CONFLICT (code) DO NOTHING;